spring.application.name=washtrack-api

base.path=/washtrack/api/v1

# PROPIEDADES PARA BASE DE DATOS MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/washtrackdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=argenisamg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# PROPIEDADES PARA FILE SYSTEM

# PROPIEDADES OAUTH

# PROPIEDADES JWT